version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    labels: [ci, dependencies]
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    labels: [dependencies]
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: cargo
    directory: /packages/desktop/src-tauri
    schedule: { interval: weekly }
    labels: [desktop, dependencies]
